### ISSUE TITLE
Proper treatment of non public datasets

### ISSUE THREAD

**Issue by andersy005** [carbonplan/leap-data-catalog#38]
This is a good start! We can punt to another PR, but I think this treatment could use a little more thinking.

Without any further messaging, it's not clear why the button is disabled. Because this is a public-facing website, it seems helpful to show a general message that the dataset is not publicly accessible. I think it'd make sense to render this at the top-level for the Zarr store, since the same thing may be applicable for users trying to open in Python?

Also in general, it's helpful to add a disabled style that's not interaction-based (e.g., greying out the button) to signal that the button isn't just broken. This is especially relevant on touch devices where the cursor style does not show up.

_Originally posted by @katamartin in https://github.com/carbonplan/leap-data-catalog/pull/37#discussion_r1577937205_

**Comment by katamartin** [comment]
I also noticed while testing https://github.com/carbonplan/leap-data-catalog/issues/41 that the hover behavior is still enabled even though the button is disabled, which is pretty confusing.
