### ISSUE TITLE
data viewer connection statuses for datasets in the catalog

### ISSUE THREAD

**Issue by andersy005** [carbonplan/leap-data-catalog#40]
<table>
<tr>
 <td>url
 <td>error
<tr>
 <td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/gpcp-feedstock/gpcp.zarr
 <td>✅ None
<tr>
 <td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/HadISST-feedstock/hadisst.zarr
 <td>✅ None
<tr>
 <td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/AGDC-feedstock/AGCD.zarr
 <td>✅ None
<tr>
 <td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/eVolv2k-feedstock/eVolv2k.zarr
 <td>No CF axes information provided and unable to infer from metadata.

<tr> 
<td> https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/LMRv2p1_MCruns_ensemble_gridded-feedstock/LMRv2p1_MCruns_ensemble_gridded.zarr
<td>No viewable variables found. Please provide a dataset with at least 2D data arrays.

<tr>
<td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/noaa-coastwatch-geopolar-sst-feedstock/noaa-coastwatch-geopolar-sst.zarr
<td>✅ None

<tr>
<td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/noaa-coastwatch-geopolar-sst-feedstock/noaa-coastwatch-geopolar-sst.zarr
<td> ⚠️ slow to load

<tr>
<td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/EOBS-feedstock/eobs-wind-speed.zarr
<td>✅ None 

<tr>
<td> https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/EOBS-feedstock/eobs-tg-tn-tx-rr-hu-pp.zarr
<td>✅ None 

<tr>
<td> https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/EOBS-feedstock/eobs-surface-downwelling.zarr
<td>✅ None 

<tr>
<td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-cmems-duacs
<td>✅ None

<tr>
<td>https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/WOA_1degree_monthly-feedstock/woa18-1deg-monthly.zarr
<td>✅ None

<tr>
<td>
https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/cesm-atm-025deg-feedstock/cesm-atm-025deg.zarr
<td>✅ None

<tr>
<td>
https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/noaa_oisst/v2.1-avhrr.zarr
<td>✅ None

<tr>
<td>
https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/soda342/5day_ice.zarr/
<td>No CF axes information provided and unable to infer from metadata.

<tr>
<td>
https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/terraclimate-feedstock/terraclimate.zarr
<td>JSON.parse: unexpected character at line 1 column 1 of the JSON data

</table>

Cc @katamartin

**Comment by katamartin** [comment]
> do you happen to know why https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/EOBS-feedstock/eobs-wind-speed.zarr shows a global view despite the dataset being regional?

It looks like the logic for locking the zoom [currently relies on check](https://github.com/carbonplan/ncview-js/blob/main/components/utils/data.js#L294-L296) against how many chunks are present for the total dataset. It seems like a safer option is to consistently block access to zoom unless a pyramid is provided. I can open a PR!

**Comment by andersy005** [comment]
> Cannot read properties of undefined (reading 'X') (@katamartin, do you happen to know what's going on here?)

- this should be addressed in https://github.com/carbonplan/ncview-js/pull/35

**Comment by katamartin** [comment]
The last CF axis issue was resolved with https://github.com/carbonplan/ncview-js/pull/41, but I'm not seeing any data show up 🤔

**Comment by katamartin** [comment]
@andersy005 the issue with `https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/terraclimate-feedstock/terraclimate.zarr` seems to be coming from `zarr-proxy` returning a 500 -- any idea what's going on? See sample request: https://ok6vedl4oj7ygb4sb2nzqvvevm0qhbbc.lambda-url.us-west-2.on.aws/ncsa.osn.xsede.org/Pangeo/pangeo-forge/terraclimate-feedstock/terraclimate.zarr/.zmetadata

**Comment by andersy005** [comment]
> The last CF axis issue was resolved with [carbonplan/ncview-js#41](https://github.com/carbonplan/ncview-js/pull/41), but I'm not seeing any data show up 🤔
> 
> When I inspect the data in the console on the frontend, it looks like the chunks are full of `0`s. Does this match your view in Python @andersy005 @norlandrhagen?

yes. i'm getting `nan` on my end.  i'm not confident about the integrity of data from this feedstock. my hunch is that this is one of the earlier feedstocks, and there's a chance nobody looked at the data once the feedstock was run ~ 2 years ago. 


```python

In [7]: ds.cn.isel(time=0, ct=0).compute()
Out[7]: 
<xarray.DataArray 'cn' (yt: 1070, xt: 1440)> Size: 6MB
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
Coordinates:
    ct       float64 8B 0.0
    time     object 8B 1992-01-05 13:00:00
  * xt       (xt) float64 12kB -279.9 -279.7 -279.4 -279.2 ... 79.42 79.65 79.88
  * yt       (yt) float64 9kB -80.02 -79.92 -79.81 -79.7 ... 78.84 78.84 78.85
Attributes:
    cell_methods:   time: mean
    long_name:      ice concentration
    time_avg_info:  average_T1,average_T2,average_DT
    units:          0-1

In [9]: ds.hi.isel(time=0).compute()
Out[9]: 
<xarray.DataArray 'hi' (yt: 1070, xt: 1440)> Size: 6MB
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
Coordinates:
    time     object 8B 1992-01-05 13:00:00
  * xt       (xt) float64 12kB -279.9 -279.7 -279.4 -279.2 ... 79.42 79.65 79.88
  * yt       (yt) float64 9kB -80.02 -79.92 -79.81 -79.7 ... 78.84 78.84 78.85
Attributes:
    cell_methods:   time: mean
    long_name:      ice thickness
    time_avg_info:  average_T1,average_T2,average_DT
    units:          m-ice
```

**Comment by norlandrhagen** [comment]
Seems like it! The data array is also named 'hi' 🥇 . I can delete this feedstock and remove it from the catalog.

**Comment by katamartin** [comment]
> > @andersy005 the issue with `https://ncview-js.staging.carbonplan.org/?dataset=https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/terraclimate-feedstock/terraclimate.zarr` seems to be coming from `zarr-proxy` returning a 500 -- any idea what's going on? See sample request: [ok6vedl4oj7ygb4sb2nzqvvevm0qhbbc.lambda-url.us-west-2.on.aws/ncsa.osn.xsede.org/Pangeo/pangeo-forge/terraclimate-feedstock/terraclimate.zarr/.zmetadata](https://ok6vedl4oj7ygb4sb2nzqvvevm0qhbbc.lambda-url.us-west-2.on.aws/ncsa.osn.xsede.org/Pangeo/pangeo-forge/terraclimate-feedstock/terraclimate.zarr/.zmetadata)
> 
> @katamartin
> 
> the metadata file contains fields with utf-16 encoding and this causes issues when the web server encodes the response:
> 
> ```python
> In [10]: zarr.util.json_loads(store['.zmetadata'])['metadata']['.zattrs']['summary']
> Out[10]: 'This archive contains a dataset of high-spatial resolution (1/24\udcc2\udcb0, ~4-km) monthly climate and climatic water balance for global terrestrial surfaces from 1958-2015. These data were created by using climatically aided interpolation, combining high-spatial resolution climatological normals from the WorldClim version 1.4 and version 2 datasets, with coarser resolution time varying (i.e. monthly) data from CRU Ts4.0 and JRA-55 to produce a monthly dataset of precipitation, maximum and minimum temperature, wind speed, vapor pressure, and solar radiation. TerraClimate additionally produces monthly surface water balance datasets using a water balance model that incorporates reference evapotranspiration, precipitation, temperature, and interpolated plant extractable soil water capacity.'
> 
> In [11]: zarr.util.json_loads(store['.zmetadata'])['metadata']['.zattrs']['summary'].encode("utf-8")
> ---------------------------------------------------------------------------
> UnicodeEncodeError                        Traceback (most recent call last)
> Cell In[11], line 1
> ----> 1 zarr.util.json_loads(store['.zmetadata'])['metadata']['.zattrs']['summary'].encode("utf-8")
> 
> UnicodeEncodeError: 'utf-8' codec can't encode characters in position 64-65: surrogates not allowed
> ```

Huh super interesting -- on my latest branch, which skips the proxy request for metadata and instead fetches metadata via a serverless function, this dataset is now accessible: https://data-viewer-git-katamartin-improve-errors-carbonplan.vercel.app/?dataset=https%3A%2F%2Fncsa.osn.xsede.org%2FPangeo%2Fpangeo-forge%2Fterraclimate-feedstock%2Fterraclimate.zarr

@andersy005 how do you feel about doing our coordinated merging?

**Comment by andersy005** [comment]
Closing this as all issues seem to have been addressed
